### ISSUE TITLE
travel checklist

### ISSUE THREAD

**Issue by neilChenXie** [neilChenXie/neilChenXie.github.io#1]
### Room

- [ ] personal clean package
- [ ] sliper
- [ ] room shirt
- [ ] room pants

### Cloth&Shoe

- [ ] shorts (above 25°C/Special)
- [ ] pants (under 25°C/Special)
- [ ] shirts (above 25°C/Special)
- [ ] hoodies (under 23°C/Special)
- [ ] shoes

### Electric Device

- [ ] Chargers
- [ ] Battery

### Document

- [ ] ID
- [ ] drive license

**Comment by neilChenXie** [comment]
### Room

- [x] personal clean package
- [x] sliper
- [x] room shirt
- [x] room pants

### Cloth&Shoe

> 天气热，保证衣服每天一件，裤子两天一条

- [x] shorts (above 25°C/Special)
- [x] pants (under 25°C/Special)
- [x] shirts (above 25°C/Special)
- [x] hoodies (under 22°C/Special)
- [x] shoes

### Electric Device

- [x] Chargers
- [x] Battery

### Must

- [x] ID
- [x] drive license
- [x] wallet
- [x] keys
